version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
